import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Righteous } from "next/font/google";
import NavigationBar from "@/components/NavigationBar";

import getServerSession from "next-auth";
import Link from "next/link";
import { SessionProvider } from "next-auth/react";
import { auth } from "../../auth";

const righteous = Righteous({
  weight: ["400"],
  subsets: ["latin"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  //const session = await getServerSession();
  const session = await auth();
  console.log("session from LAYOUT :>> ", session);

  console.log("RootLayout :>> ");
  return (
    <html lang="en">
      <SessionProvider>
        <body
          className={`${geistSans.variable} ${geistMono.variable}`}
          style={{ margin: 0, padding: 0 }}
        >
          <video
            autoPlay
            loop
            muted
            playsInline
            style={{
              position: "fixed",
              top: 0,
              left: 0,
              width: "100vw",
              height: "100vh",
              objectFit: "cover",
              zIndex: -1, // Puts the video behind content
            }}
          >
            <source src="/video2.mp4" type="video/mp4" />
          </video>

          <div
            style={{
              display: "flex",
              flexDirection: "column",
              alignItems: "center",
            }}
          >
            <Link href="/">
              <h1 className={`homeTitle ${righteous.className}`}>Cosmoquiz</h1>
            </Link>
            <NavigationBar sessionProp={session} />
            {children}
          </div>
        </body>
      </SessionProvider>
    </html>
  );
}
